export const timelineData = [
  {
    year: "1962",
    title: "INCOSPAR Formation",
    description: "Dr. Vikram Sarabhai establishes Indian National Committee for Space Research, laying the foundation for India's space program.",
    icon: "flag",
    iconColor: "stellar-blue",
    borderColor: "stellar-blue",
    animate: false,
  },
  {
    year: "1969",
    title: "ISRO Establishment",
    description: "Indian Space Research Organisation officially formed under Department of Atomic Energy, beginning India's organized space efforts.",
    icon: "rocket",
    iconColor: "galaxy-purple",
    borderColor: "galaxy-purple",
    animate: false,
  },
  {
    year: "1975",
    title: "Aryabhatta Launch",
    description: "India's first satellite launched from Soviet Union, marking the beginning of the country's journey into space exploration.",
    icon: "satellite",
    iconColor: "isro-gold",
    borderColor: "isro-gold",
    animate: false,
  },
  {
    year: "1980",
    title: "Rohini Satellite",
    description: "First satellite launched by India's own rocket SLV-3, achieving complete technological independence in satellite deployment.",
    icon: "satellite",
    iconColor: "mission-orange",
    borderColor: "mission-orange",
    animate: false,
  },
  {
    year: "1984",
    title: "Rakesh Sharma in Space",
    description: "Squadron Leader Rakesh Sharma becomes the first Indian to travel to space aboard Soviet Soyuz T-11 spacecraft.",
    icon: "rocket",
    iconColor: "stellar-blue",
    borderColor: "stellar-blue",
    animate: false,
  },
  {
    year: "1988",
    title: "IRS-1A Launch",
    description: "India's first operational remote sensing satellite launched, revolutionizing earth observation and resource management.",
    icon: "globe",
    iconColor: "galaxy-purple",
    borderColor: "galaxy-purple",
    animate: false,
  },
  {
    year: "1993",
    title: "PSLV First Flight",
    description: "Polar Satellite Launch Vehicle makes debut flight, though unsuccessful, leading to India's most reliable rocket series.",
    icon: "rocket",
    iconColor: "isro-gold",
    borderColor: "isro-gold",
    animate: false,
  },
  {
    year: "2001",
    title: "GSLV Debut",
    description: "Geosynchronous Satellite Launch Vehicle first flight, enabling India to launch heavier communication satellites.",
    icon: "rocket",
    iconColor: "mission-orange",
    borderColor: "mission-orange",
    animate: false,
  },
  {
    year: "2008",
    title: "Chandrayaan-1",
    description: "India's first lunar mission discovers water molecules on the Moon, establishing India as a major player in lunar exploration.",
    icon: "moon",
    iconColor: "stellar-blue",
    borderColor: "stellar-blue",
    animate: false,
  },
  {
    year: "2013",
    title: "Mars Orbiter Mission Launch",
    description: "Mangalyaan launched towards Mars, beginning India's first interplanetary mission with innovative fuel-efficient trajectory.",
    icon: "globe",
    iconColor: "galaxy-purple",
    borderColor: "galaxy-purple",
    animate: false,
  },
  {
    year: "2014",
    title: "Mars Orbit Achievement",
    description: "Mangalyaan successfully reaches Mars orbit in the first attempt, making India the fourth country to reach Mars.",
    icon: "globe",
    iconColor: "mission-orange",
    borderColor: "mission-orange",
    animate: false,
  },
  {
    year: "2017",
    title: "104 Satellites Record",
    description: "PSLV-C37 sets world record by launching 104 satellites in single mission, demonstrating India's launch capabilities.",
    icon: "satellite",
    iconColor: "isro-gold",
    borderColor: "isro-gold",
    animate: false,
  },
  {
    year: "2019",
    title: "Chandrayaan-2 Launch",
    description: "India's second lunar mission launched with orbiter, lander and rover, advancing lunar exploration technology.",
    icon: "moon",
    iconColor: "stellar-blue",
    borderColor: "stellar-blue",
    animate: false,
  },
  {
    year: "2023",
    title: "Chandrayaan-3 Success",
    description: "Historic soft landing near Moon's south pole, making India the 4th country to achieve lunar landing and first near the south pole.",
    icon: "moon",
    iconColor: "galaxy-purple",
    borderColor: "galaxy-purple",
    animate: true,
  },
  {
    year: "2023",
    title: "Aditya-L1 Solar Mission",
    description: "India's first solar observation mission launched to study the Sun's corona and solar wind from L1 Lagrange point.",
    icon: "globe",
    iconColor: "mission-orange",
    borderColor: "mission-orange",
    animate: true,
  },
];

export const missionsData = [
  {
    title: "Chandrayaan-3",
    status: "Success",
    description: "India's third lunar exploration mission achieved historic soft landing near the Moon's south pole in August 2023.",
    year: "2023",
    image: "https://pixabay.com/get/gefba251e458a711cb4588c6a6da8914d339ca0d6d004993112489b610481d60aabb0a40d5db3c37d26f0691c430cd60e_1280.jpg",
    alt: "Lunar surface exploration",
  },
  {
    title: "Mangalyaan",
    status: "Success",
    description: "India's first interplanetary mission to Mars, achieving orbit in the first attempt at a record low cost.",
    year: "2014",
    image: "https://images.unsplash.com/photo-1614728423169-3f65fd722b7e?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=300",
    alt: "Mars surface exploration",
  },
  {
    title: "PSLV Program",
    status: "Ongoing",
    description: "India's workhorse rocket launcher with over 50 successful missions, setting multiple world records.",
    year: "1993-Present",
    image: "https://images.unsplash.com/photo-1517976487492-5750f3195933?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=300",
    alt: "Rocket launch with flames and smoke",
  },
  {
    title: "Aditya-L1",
    status: "Active",
    description: "India's first solar observation mission studying the Sun's corona and solar wind from the L1 Lagrange point.",
    year: "2023",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=300",
    alt: "Solar observation with sun and corona",
  },
  {
    title: "GSLV Program",
    status: "Ongoing",
    description: "Geosynchronous Satellite Launch Vehicle program enabling heavy satellite deployment and reducing foreign dependency.",
    year: "2001-Present",
    image: "https://images.unsplash.com/photo-1421789665209-c9b2a435e3dc?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=300",
    alt: "Satellite with solar panels in space",
  },
  {
    title: "Gaganyaan",
    status: "Upcoming",
    description: "India's first human spaceflight mission, set to carry Indian astronauts to low Earth orbit by 2025.",
    year: "2025",
    image: "https://images.unsplash.com/photo-1446776877081-d282a0f896e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=300",
    alt: "Advanced space station with Earth view",
  },
];

export const achievementsData = [
  {
    title: "Most Cost-Effective Mars Mission",
    description: "Mangalyaan reached Mars at just $74 million - less than the budget of the movie \"Gravity\"",
    stat: "$74 Million Total Cost",
    icon: "dollar",
    iconColor: "mission-orange",
    borderColor: "mission-orange",
  },
  {
    title: "Record Satellite Launch",
    description: "PSLV-C37 launched 104 satellites in a single mission, setting a world record",
    stat: "104 Satellites in One Launch",
    icon: "satellite",
    iconColor: "stellar-blue",
    borderColor: "stellar-blue",
  },
  {
    title: "First Attempt Mars Success",
    description: "Only country to reach Mars orbit successfully in the first attempt",
    stat: "100% Success Rate",
    icon: "trophy",
    iconColor: "isro-gold",
    borderColor: "isro-gold",
  },
  {
    title: "First Lunar South Pole Landing",
    description: "Chandrayaan-3 achieved the first successful soft landing near Moon's south pole",
    stat: "Historic Achievement",
    icon: "moon",
    iconColor: "galaxy-purple",
    borderColor: "galaxy-purple",
  },
];

export const costComparisonData = [
  { mission: "ISRO Mars Mission", cost: 74, color: "bg-mission-orange" },
  { mission: "NASA MAVEN", cost: 671, color: "bg-blue-500" },
  { mission: "ESA Mars Express", cost: 386, color: "bg-green-500" },
];

export const leadersData = [
  {
    name: "Dr. Vikram Sarabhai",
    title: "Father of Indian Space Program",
    description: "Visionary physicist who established INCOSPAR in 1962 and founded ISRO in 1969. His philosophy emphasized space technology for national development rather than prestige projects.",
    years: "1919 - 1971",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Dr_Vikram_Sarabhai.jpg/300px-Dr_Vikram_Sarabhai.jpg",
    alt: "Dr. Vikram Sarabhai portrait",
    achievements: ["Founded ISRO", "Established space program philosophy", "First rocket launch from Thumba"],
  },
  {
    name: "Dr. A.P.J. Abdul Kalam",
    title: "Missile Man of India",
    description: "Aerospace engineer who led India's missile and nuclear programs. Key architect of Agni and Prithvi missiles, later became India's 11th President.",
    years: "1931 - 2015",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/A._P._J._Abdul_Kalam.jpg/300px-A._P._J._Abdul_Kalam.jpg",
    alt: "Dr. A.P.J. Abdul Kalam portrait",
    achievements: ["Developed Agni missile series", "Led SLV-3 project", "11th President of India"],
  },
  {
    name: "Dr. K. Sivan",
    title: "Rocket Man (Former ISRO Chairman)",
    description: "Cryogenic expert who led ISRO during Chandrayaan-2 and multiple GSLV missions. Known for advancing India's heavy-lift launch capabilities.",
    years: "1957 - Present",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Dr._K._Sivan.jpg/300px-Dr._K._Sivan.jpg",
    alt: "Dr. K. Sivan portrait",
    achievements: ["Led Chandrayaan-2", "Advanced GSLV program", "Cryogenic technology pioneer"],
  },
  {
    name: "Dr. S. Somnath",
    title: "Current ISRO Chairman",
    description: "Current ISRO chief who successfully led Chandrayaan-3 mission. Advancing Gaganyaan human spaceflight program and next-generation launch vehicles.",
    years: "1963 - Present",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/S._Somanath.jpg/300px-S._Somanath.jpg",
    alt: "Dr. S. Somnath portrait",
    achievements: ["Chandrayaan-3 success", "Leading Gaganyaan", "SSLV development"],
  },
  {
    name: "Dr. M. Annadurai",
    title: "Moon Man of India",
    description: "Project director of Chandrayaan-1 mission that discovered water on Moon. Led multiple planetary missions including Mars Orbiter Mission.",
    years: "1958 - Present",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/M._Annadurai.jpg/300px-M._Annadurai.jpg",
    alt: "Dr. M. Annadurai portrait",
    achievements: ["Chandrayaan-1 water discovery", "Mars Orbiter Mission", "Planetary exploration pioneer"],
  },
  {
    name: "Dr. Tessy Thomas",
    title: "Missile Woman of India",
    description: "First woman scientist to head missile project in India. Led Agni-IV and Agni-V missile development programs at DRDO.",
    years: "1963 - Present",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tessy_Thomas.jpg/300px-Tessy_Thomas.jpg",
    alt: "Dr. Tessy Thomas portrait",
    achievements: ["Led Agni-IV project", "Advanced missile technology", "Women in STEM pioneer"],
  },
];

export const galleryData = [
  {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/PSLV-C25_successful_launch.jpg/500px-PSLV-C25_successful_launch.jpg",
    alt: "PSLV-C25 Mars Orbiter Mission launch",
    title: "Mars Orbiter Mission Launch",
    year: "2013",
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Chandrayaan-3_Mission_logo.png/400px-Chandrayaan-3_Mission_logo.png",
    alt: "Chandrayaan-3 mission emblem",
    title: "Chandrayaan-3 Mission",
    year: "2023",
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/ISRO_PSLV-C37_104_satellites.jpg/500px-ISRO_PSLV-C37_104_satellites.jpg",
    alt: "PSLV-C37 with 104 satellites",
    title: "World Record Launch",
    year: "2017",
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Sriharikota_Range_%28SHAR%29.jpg/500px-Sriharikota_Range_%28SHAR%29.jpg",
    alt: "ISRO Sriharikota launch complex",
    title: "Satish Dhawan Space Centre",
    year: "Launch Facility",
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/GSLV_Mark_III_M1_launching_Chandrayaan-2.jpg/400px-GSLV_Mark_III_M1_launching_Chandrayaan-2.jpg",
    alt: "GSLV Mark III launching Chandrayaan-2",
    title: "Chandrayaan-2 Launch",
    year: "2019",
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Aryabhatta_satellite.jpg/400px-Aryabhatta_satellite.jpg",
    alt: "India's first satellite Aryabhatta",
    title: "Aryabhatta Satellite",
    year: "1975",
  },
];
